name: todo_flutter_moor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #for moor
  cupertino_icons: ^1.0.2
  moor_flutter: ^4.0.0
  provider: ^6.0.2

  #for drift
  drift: ^1.4.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0

  #for sqlite
  sqflite: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  #moor_generator: ^4.6.0+1
  build_runner: ^2.1.7

  #for drift
  drift_dev: ^1.4.0

flutter:

  uses-material-design: true